import type { Metadata } from "next";
import { Diphylleia } from "next/font/google";
import "./globals.css";

const diphylleia = Diphylleia({
  variable: "--font-diphylleia",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${diphylleia.variable} ${diphylleia.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
