import type { Metadata } from "next";
import { Diphylleia } from "next/font/google";
import "./globals.css";

const diphylleia = Diphylleia({
  variable: "--font-diphylleia",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Diphylleia&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${diphylleia.variable} ${diphylleia.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
